### ISSUE TITLE
HRRR as Zarr on AWS

### ISSUE THREAD

**Issue by rsignell-usgs** [blaylockbk/HRRR_archive_download#2]
@blaylockbk , this is probably the wrong place to raise this, but I saw in your [HRRR Archive FAQ](http://home.chpc.utah.edu/~u0553130/Brian_Blaylock/hrrr_FAQ.html), you said: 

> One day, we hope this data will be archived elsewhere that is more accessible to everyone. Perhaps soon it will be hosted by Amazon by their Opendata initiative. I would advocate to keep it in the GRIB2 format (the original format it is output as), but it would also be nice to store the data in a "cloud-friendly" format such as zarr. 

To have archived HRRR data in Zarr would be AMAZING.   We were trying to figure out how to download 1 year of HRRR surface fields to drive a Delaware Bay hydrodynamics simulation, and thinking how useful it would be to have the data on AWS.    We could store as Zarr but create GRIB-on-demand service for those who need it.   I've been active on the [Pangeo](pangeo.io) project, and we have some tools now that could make the conversion, chunking and upload to cloud much easier.   And I'd be happy to help out. 

@zflamig, you guys would be up for [a proposal ](https://aws.amazon.com/opendata/open-data-sponsorship-program/)on this, right ?

**Comment by blaylockbk** [comment]
Hi!
Not the wrong place to ask. I'm no longer at the University of Utah working on this project, but yes, that is the plan! And I'm excited to see it happen. As far as I understand, the work is currently underway and a *big* chunk has already been moved to AWS. @zflamig @johnhorel @mesowx would know more than I do about that effort.

**Comment by johnhorel** [comment]
Yep, several months in zarr format are available already in AWS behind the curtain. We are grateful to @zflamig and the AWS Open Data Program to make that possible. We'll let you know as soon as the project goes live. Taylor Gowan is working on example codes for people to start from.  Here's a taste to show the 96 chunks. Dang- you won't be in just one chunk, but stitching a few together is not a big deal.
![image](https://user-images.githubusercontent.com/2700247/93643928-323a3780-f9be-11ea-9a1d-ac9538414821.png)

**Comment by rsignell-usgs** [comment]
@johnhorel , that's super cool!    You mean those are the chunks within the single Zarr dataset, right?

**Comment by johnhorel** [comment]
Yes, there is a directory structure to tunnel down until you get the specific field/vertical level/YYMMDDHH but then in one directory there are 96 chunks within which are the all forecasts for that model run so it is easier to do data analytics. It will be straightforward to grab what you need with the understanding of how complex NCEP has the naming convention for types of levels, variables, etc.

**Comment by rsignell-usgs** [comment]
@johnhorel, I'm trying to create a "best time series" from HRRR for the purpose of providing boundary conditions for coastal ocean models.   I downloaded all the F01 hour data from AWS in grib format for 2019 as a test, but found there were 42 missing files:
```
fmissing = ['noaa-hrrr-bdp-pds/hrrr.20190310/conus/hrrr.t02z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190310/conus/hrrr.t03z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190310/conus/hrrr.t04z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190310/conus/hrrr.t05z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190310/conus/hrrr.t06z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190310/conus/hrrr.t07z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190310/conus/hrrr.t08z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190310/conus/hrrr.t09z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190310/conus/hrrr.t10z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190310/conus/hrrr.t11z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190310/conus/hrrr.t12z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190310/conus/hrrr.t13z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190310/conus/hrrr.t14z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190310/conus/hrrr.t15z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190310/conus/hrrr.t16z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190310/conus/hrrr.t17z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190310/conus/hrrr.t18z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190310/conus/hrrr.t19z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190310/conus/hrrr.t20z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190310/conus/hrrr.t21z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190310/conus/hrrr.t22z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190310/conus/hrrr.t23z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190311/conus/hrrr.t13z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190311/conus/hrrr.t14z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190311/conus/hrrr.t15z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190311/conus/hrrr.t16z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190503/conus/hrrr.t23z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190504/conus/hrrr.t10z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190504/conus/hrrr.t11z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190504/conus/hrrr.t12z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190504/conus/hrrr.t13z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190504/conus/hrrr.t14z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190504/conus/hrrr.t18z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190504/conus/hrrr.t19z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190504/conus/hrrr.t20z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190504/conus/hrrr.t21z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190504/conus/hrrr.t22z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190504/conus/hrrr.t23z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190906/conus/hrrr.t08z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20190906/conus/hrrr.t09z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20191122/conus/hrrr.t17z.wrfsfcf01.grib2',
 'noaa-hrrr-bdp-pds/hrrr.20191122/conus/hrrr.t18z.wrfsfcf01.grib2']
```

Can you confirm that those are indeed missing?
If so, what actions would you recommend to create a  best time series without gaps?

**Comment by johnhorel** [comment]
Rich-


Thanks, not too surprised as there are plenty of ways real-time access can get mucked up. The main thing in your favor is all the data are on both google and AWS now. You should be able to fill in from those sources and plan to use them for other years. Their archives are complete.

NOAA page link: https://registry.opendata.aws/noaa-hrrr-pds/

https://console.cloud.google.com/storage/browser/high-resolution-rapid-refresh?project=gcp-public-data-weather


We are working to get the zarr archive which will be our focus public on AWS in the next few weeks. More details  on that to follow on the hrrr.chpc.utah.edu page.


Regards

john

_________

Please do not feel obligated to respond to this email outside of your normal working hours

_________

John Horel

Professor, Chair

Department of Atmospheric Sciences

University of Utah

john.horel@utah.edu

cell: (801) 870-9450

office: (801) 581-7091


________________________________

**Comment by johnhorel** [comment]
Oh my bad. I didn't pay attention that you were already getting it from AWS. Try google? Otherwise, there are glitches where the model runs just may not be available. We're interested in these outages too for documenting gaps in the zarr archive but just haven't got there yet.


john


_________

Please do not feel obligated to respond to this email outside of your normal working hours

_________

John Horel

Professor, Chair

Department of Atmospheric Sciences

University of Utah

john.horel@utah.edu

cell: (801) 870-9450

office: (801) 581-7091

________________________________

**Comment by johnhorel** [comment]
Oh my bad. I didn't pay attention that you were already retrieving the files from AWS. Try google? We're interested in these outages too for documenting gaps in the zarr archive but just haven't got there yet.


john


_________

Please do not feel obligated to respond to this email outside of your normal working hours

_________

John Horel

Professor, Chair

Department of Atmospheric Sciences

University of Utah

john.horel@utah.edu

cell: (801) 870-9450

office: (801) 581-7091

________________________________

**Comment by rsignell-usgs** [comment]
@johnhorel , I checked Google Cloud, and the same 42 files seem to be missing.   😞

**Comment by ktyle** [comment]
Wonder if these gaps correspond to instances where the NCEP model production suite had problems that forced runs to be scrubbed.

**Comment by rsignell-usgs** [comment]
@ktyle, yipes, it didn't occur to me that these might be actual gaps in the forecast -- I assumed they were just files that failed to transfer at some point in the workflow.

@johnhorel , if it's not going to be possible to recover these files, could you please let me know so I can develop a workaround filling in with other forecast hours from the last good forecasts before the gaps?

**Comment by rsignell-usgs** [comment]
@johnhorel, I wrote a script to fill the gaps with the best available previous long forecast (from the forecasts at 0, 6, 12, 18 hours).
If the missing original grib files are actually available, I'll use those instead!

**Comment by johnhorel** [comment]
Sorry for the hassle Rich but sounds like a good plan.

regards

john


_________

Please do not feel obligated to respond to this email outside of your normal working hours

_________

John Horel

Professor, Chair

Department of Atmospheric Sciences

University of Utah

john.horel@utah.edu

cell: (801) 870-9450

office: (801) 581-7091

________________________________

**Comment by rustyconover** [comment]
Is there a way to track the availability in Zarr format?  Or see some examples of the conversion?

I'm interested in applying Uber's H3 library to downsample the forecasts and allow accessibility for wider geographic areas without having to download and interpolate the full resolution forecast products.

**Comment by johnhorel** [comment]
Rusty-


We're in the process of getting the docs in place with examples. Thanks for your interest. It might be worth a quick call if you'd like as we'd like to build up some use cases.


Regards

john


_________

Please do not feel obligated to respond to this email outside of your normal working hours

_________

John Horel

Professor, Chair

Department of Atmospheric Sciences

University of Utah

john.horel@utah.edu

cell: (801) 870-9450

office: (801) 581-7091

________________________________

**Comment by rustyconover** [comment]
@johnhorel Just sent you a personal email.

**Comment by blaylockbk** [comment]
AWS announced HRRR as a new public dataset on January 14, 2021: https://aws.amazon.com/about-aws/whats-new/2021/01/new-aws-public-datasets-available/

GRIB2 bucket explorer: https://noaa-hrrr-bdp-pds.s3.amazonaws.com/index.html
Zarr bucket explorer: https://hrrrzarr.s3.amazonaws.com/index.html

**Comment by johnhorel** [comment]
Yep we still have bunches to do. Hoping most people will ignore our zarr archive for a couple more weeks. John

John Horel
Professor, Chair
Department of Atmospheric Sciences
University of Utah
Cell 801 870-9450
john.horel@utah.edu
________________________________

**Comment by rsignell-usgs** [comment]
@johnhorel, I finished my processing of the HRRR 2019 data.   I created a "best time series" with my variables of interest as a single Zarr dataset.   I chunked the (time=8760, y=1059, x=1799) arrays into (time=144, y=300, x=300) chunks (50MB).  

This allows for reasonable access times whether acquiring the entire US at a single time step, or obtaining the entire archive time series at a specified location.   

Here's a few screengrabs from this [example analysis/visualization notebook](https://nbviewer.jupyter.org/gist/rsignell-usgs/4edfff890a7a18f97eaef42d647ec534):

![2021-01-20_10-29-30](https://user-images.githubusercontent.com/1872600/105197552-b803f600-5b0a-11eb-9e69-8801eb05b064.png)
![2021-01-20_10-30-23](https://user-images.githubusercontent.com/1872600/105197559-ba665000-5b0a-11eb-9b1f-364f856aa0cf.png)
![2021-01-20_10-30-51](https://user-images.githubusercontent.com/1872600/105197570-bcc8aa00-5b0a-11eb-9191-b5ad8264abf0.png)
 
To create this single cloud-optimized Zarr dataset from the initial GRIB2 files, I used basically three steps, captured in these notebooks:
1. [Download](https://nbviewer.jupyter.org/gist/rsignell-usgs/736c4ec1ba37e39fc085ccc562d05867)
1. [Fill Gaps](https://nbviewer.jupyter.org/gist/rsignell-usgs/0488c2a690b34654f658b7eca2dab465)
1. [Rechunk](https://nbviewer.jupyter.org/gist/rsignell-usgs/eb59ede31eb4d0bc6434b32f66d30a6e)

My documentation is a bit light but I'd be happy to discuss further here if there is interest. 

Ping @ktyle , @abarciauskas-bgse, @zflamig

**Comment by rsignell-usgs** [comment]
ping @taylorgowan, for an example of whole domain as Zarr, hoping it's useful.  Ping me if you would like something different!

**Comment by johnhorel** [comment]
Rich-


Yes, was discussing with the group that we're missing some aspects of what has and is being done. Your comments yesterday were very pertinent.


Regards

john



_________

Please do not feel obligated to respond to this email outside of your normal working hours

_________

John Horel

Professor, Chair

Department of Atmospheric Sciences

University of Utah

***@***.***

cell: (801) 870-9450

office: (801) 581-7091

________________________________
